#!/usr/bin/python
import sys,os
s=''
if len(sys.argv)>1:
    s=sys.argv[1]
if s=='install':
    os.system('cp -f .vimrc ~/.vimrc')
elif s=='getlocal':
    os.system('cp -f ~/.vimrc .vimrc')
elif s=='diff':
    os.system('git diff ~/.vimrc .vimrc')
elif s=='vundle':
    os.system("git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim")
else:
    print('Usage: ./update [getlocal] [install] [diff] [vundle]')
